import 'records/domain/entities/resource_spec.dart';

/// true  = sign in with the Elyvori API and show the live agents dashboard.
/// false = a standalone offline-first app that opens straight on its modules.
const bool useElyvoriAgents = false;

/// The modules of this app, generated by Elyvori from the client's request.
const List<ResourceSpec> appResources = <ResourceSpec>[

];
